spring:
  datasource:
    url: jdbc:mysql://10.1.2.100:3306/unimax55_develop
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect